return {{[ [[Fango]] ] = {2},[ [[Ghaik]] ] = {3},[ [[Rancor]] ] = {4},[ [[Kaki]] ] = {5},[ [[Chiles]] ] = {6},[ [[Glitch]] ] = {7},[ [[Parrot]] ] = {8},[ [[Celeste]] ] = {9},[ [[Zer]] ] = {10},[ [[Mond]] ] = {11},[ [[Abelian]] ] = {12},[ [[Vulkan]] ] = {13},[ [[Tavoli]] ] = {14},[ [[Ninehundred]] ] = {15},[ [[Volarys]] ] = {16},[ [[Vermin]] ] = {17},[ [[Gravman]] ] = {18},[ [[Meista]] ] = {19},[ [[Chronos]] ] = {20},[ [[Kylise]] ] = {21},[ [[Jarr]] ] = {22},[ [[Asha]] ] = {23},[ [[Kali]] ] = {24},[ [[Cheddar]] ] = {25},[ [[Sludge]] ] = {26},[ [[Rawil]] ] = {27},[ [[Aginor]] ] = {28},[ [[Dazer]] ] = {29},[ [[Draconixs]] ] = {30},[ [[Psiator]] ] = {31},[ [[Eanruig]] ] = {32},[ [[Blaset]] ] = {33},[ [[Image]] ] = {34},[ [[Claap]] ] = {35},[ [[Photon]] ] = {36},[ [[Zygarth]] ] = {37},[ [[Cosmus]] ] = {38},[ [[Language]] ] = {39},[ [[Ethan]] ] = {40},[ [[Xanur]] ] = {41},[ [[Tysthet]] ] = {42},[ [[Kiron]] ] = {43},[ [[Flood]] ] = {44},[ [[Jump]] ] = {45},[ [[Spuati]] ] = {46},[ [[Brencis]] ] = {47},[ [[Forseti]] ] = {48},[ [[NinehundreD]] ] = {49},[ [[Thirdeye]] ] = {50},[ [[Ellogovna]] ] = {51},[ [[Ramahdon]] ] = {52},[ [[Essel]] ] = {53},[ [[Ore]] ] = {54},[ [[Gti]] ] = {55},[ [[Arccot]] ] = {56},},
{[ [[w1name]] ] = [[Green Destiny]],[ [[w1keyword]] ] = [[destiny]],},
{[ [[w2name]] ] = [[SPIN MOVE]],[ [[w1keyword]] ] = [[ramawield]],[ [[w1name]] ] = [[HE'S ON FIRE]],[ [[w2keyword]] ] = [[calpchak32b]],},
{[ [[w2name]] ] = [[Malevolence]],[ [[w1keyword]] ] = [[extir]],[ [[w1name]] ] = [[Extirpation]],[ [[w2keyword]] ] = [[malev]],},
{[ [[w1name]] ] = [[Frostie catches Snowflakes]],[ [[w1keyword]] ] = [[apple]],},
{[ [[w2name]] ] = [[pure psi-blade]],[ [[w1keyword]] ] = [[veng]],[ [[w1name]] ] = [[Great Vengeance]],[ [[w2keyword]] ] = [[chiles]],},
{[ [[w1name]] ] = [[Glitch]],[ [[w1keyword]] ] = [[glitch]],},
{[ [[w1name]] ] = [[Pernach of domination]],[ [[w1keyword]] ] = [[30602116448]],},
{[ [[w1name]] ] = [[a shiny sword]],[ [[w1keyword]] ] = [[15387031339]],},
{[ [[w2keyword]] ] = [[xanur.off]],[ [[w1keyword]] ] = [[xanur.wield]],[ [[w1name]] ] = [[Xanur's Masamune]],[ [[w2name]] ] = [[Xanur's Murasame]],},
{[ [[w1name]] ] = [[Fire]],[ [[w1keyword]] ] = [[tranquil]],},
{[ [[w1name]] ] = [[A dragon-blade]],[ [[w1keyword]] ] = [[dragon bone blade sword hitgear]],},
{[ [[w2keyword]] ] = [[lordkrd]],[ [[w1keyword]] ] = [[lordkdr]],[ [[w1name]] ] = [[A Winged Angel]],[ [[w2name]] ] = [[A Winged Devil]],},
{[ [[w2keyword]] ] = [[tavclawright]],[ [[w1keyword]] ] = [[tavclawleft]],[ [[w1name]] ] = [[Intinn]],[ [[w2name]] ] = [[Aigne]],},
{[ [[w1name]] ] = [[Gotcha!]],[ [[w1keyword]] ] = [[got]],},
{[ [[w2keyword]] ] = [[exantus]],[ [[w1keyword]] ] = [[excelsior]],[ [[w1name]] ] = [[Excelsior V]],[ [[w2name]] ] = [[Exantus V]],},
{[ [[w2name]] ] = [[an ant chakram]],[ [[w1keyword]] ] = [[15604912483]],[ [[w1name]] ] = [[an ant chakram]],[ [[w2keyword]] ] = [[15713292332]],},
{[ [[w2keyword]] ] = [[gravman3]],[ [[w1keyword]] ] = [[gravman1]],[ [[w1name]] ] = [[gravmannnnn]],[ [[w2name]] ] = [[gravman]],},
{[ [[w2name]] ] = [[Revenant's Blade]],[ [[w1keyword]] ] = [[meistawield]],[ [[w1name]] ] = [[Sword of the Scourge]],[ [[w2keyword]] ] = [[meistaoffhand]],},
{[ [[w1name]] ] = [[Trained Attack Sprite]],[ [[w1keyword]] ] = [[sprite]],},
{[ [[w1name]] ] = [[a saber of pure light]],[ [[w1keyword]] ] = [[ky]],},
{[ [[w2name]] ] = [[RAVAGED VIRGIN SOULS]],[ [[w1keyword]] ] = [[gallahwie]],[ [[w1name]] ] = [[TAINT OF THE RAVAGED]],[ [[w2keyword]] ] = [[galla]],},
{[ [[w2keyword]] ] = [[fear]],[ [[w1keyword]] ] = [[pain]],[ [[w1name]] ] = [[ Pain]],[ [[w2name]] ] = [[ Fear]],},
{[ [[w2name]] ] = [[Whispers of the Muse]],[ [[w1keyword]] ] = [[wrath]],[ [[w1name]] ] = [[Kali's Wrath]],[ [[w2keyword]] ] = [[calpchak42c4]],},
{[ [[w2keyword]] ] = [[calpchak2c]],[ [[w1keyword]] ] = [[calpchak32]],[ [[w1name]] ] = [[CHEDDAR]],[ [[w2name]] ] = [[CHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEZE]],},
{[ [[w2name]] ] = [[Sludge's Offhand]],[ [[w1keyword]] ] = [[calpchak32c]],[ [[w1name]] ] = [[Sludge's Wield]],[ [[w2keyword]] ] = [[calpchak2]],},
{[ [[w2keyword]] ] = [[rawil6]],[ [[w1keyword]] ] = [[rawil5]],[ [[w1name]] ] = [[a sharpened flesh-tattered kobold spine]],[ [[w2name]] ] = [[a sharpened flesh-tattered goblin spine]],},
{[ [[w2keyword]] ] = [[aginorwield]],[ [[w1keyword]] ] = [[aginoroffh]],[ [[w1name]] ] = [[Kiss of the Dragkhar]],[ [[w2name]] ] = [[Myrddraal's Blade]],},
{[ [[w2keyword]] ] = [[spuati]],[ [[w1keyword]] ] = [[snuffle]],[ [[w1name]] ] = [[manna hat rack]],[ [[w2name]] ] = [[a tan ham crank]],},
{[ [[w2name]] ] = [[Thor]],[ [[w1keyword]] ] = [[loki]],[ [[w1name]] ] = [[Loki]],[ [[w2keyword]] ] = [[thor]],},
{[ [[w2name]] ] = [[Renamed Chakram Two]],[ [[w1keyword]] ] = [[mainchak]],[ [[w1name]] ] = [[Renamed Chakram One]],[ [[w2keyword]] ] = [[offchak]],},
{[ [[w2keyword]] ] = [[eanruigo]],[ [[w1keyword]] ] = [[eanruigw]],[ [[w1name]] ] = [[Chondrite Longsword]],[ [[w2name]] ] = [[Chondrite Shortsword]],},
{[ [[w2keyword]] ] = [[mandeljaroff]],[ [[w1keyword]] ] = [[mandeljar]],[ [[w1name]] ] = [[Mandel's Greater Sword]],[ [[w2name]] ] = [[Mandel's Great Sword]],},
{[ [[w2keyword]] ] = [[Remorse]],[ [[w1keyword]] ] = [[Bored]],[ [[w1name]] ] = [[Bored]],[ [[w2name]] ] = [[Remorse]],},
{[ [[w1name]] ] = [[CLICK CLICK]],[ [[w1keyword]] ] = [[calpchak]],},
{[ [[w1name]] ] = [[A winged angel]],[ [[w1keyword]] ] = [[wing]],},
{[ [[w2name]] ] = [[zygarth]],[ [[w1keyword]] ] = [[zygarth]],[ [[w1name]] ] = [[Zygarth's silver sword]],},
{[ [[w1name]] ] = [[Olorin's Bane]],[ [[w1keyword]] ] = [[bronxwield]],},
{[ [[w2name]] ] = [[Left Chakram]],[ [[w1keyword]] ] = [[language1]],[ [[w1name]] ] = [[Right Chakram]],[ [[w2keyword]] ] = [[language2]],},
{[ [[w1name]] ] = [[Pernach of domination]],[ [[w1keyword]] ] = [[30480577151]],},
{[ [[w2keyword]] ] = [[xanur.off]],[ [[w1keyword]] ] = [[xanur.wield]],[ [[w1name]] ] = [[Xanur's Masamune]],[ [[w2name]] ] = [[Xanur's Murasame]],},
{[ [[w1name]] ] = [[Malicious Whispers]],[ [[w1keyword]] ] = [[malicious]],},
{[ [[w2name]] ] = [[Loradon's Justice]],[ [[w1keyword]] ] = [[islene]],[ [[w1name]] ] = [[Islene's Fury]],[ [[w2keyword]] ] = [[loradon]],},
{[ [[w1name]] ] = [[TICKLE FIGHT]],[ [[w1keyword]] ] = [[hitt]],},
{[ [[w2name]] ] = [[chakram arccotmain]],[ [[w1keyword]] ] = [[arccotoff]],[ [[w1name]] ] = [[chakram arccotoff]],[ [[w2keyword]] ] = [[arccotmain]],},
{[ [[w2name]] ] = [[a tan ham crank]],[ [[w1keyword]] ] = [[snuffle]],[ [[w1name]] ] = [[manna hat rack]],[ [[w2keyword]] ] = [[spuati]],},
{[ [[w2name]] ] = [[frostbite]],[ [[w1keyword]] ] = [[icicle]],[ [[w1name]] ] = [[An icicle]],[ [[w2keyword]] ] = [[frostbite]],},
{[ [[w2keyword]] ] = [[forseti]],[ [[w1keyword]] ] = [[forseti]],[ [[w1name]] ] = [[Fleshslicer]],[ [[w2name]] ] = [[Fleshrender]],},
{[ [[w2name]] ] = [[*-<AGONY>-*]],[ [[w1keyword]] ] = [[pain]],[ [[w1name]] ] = [[*-<PAIN>-*]],[ [[ws2keyword]] ] = [[agony]],},
{[ [[w1name]] ] = [[Bacon Buster]],[ [[w1keyword]] ] = [[bacon]],},
{[ [[w1name]] ] = [[Demand]],[ [[w1keyword]] ] = [[Demand]],},
{[ [[w2name]] ] = [[TICKLE FIGHT]],[ [[w1keyword]] ] = [[pointy stick crom lordgear hitt]],[ [[w1name]] ] = [[I AM BEYONCE, ALWAYS]],[ [[w2keyword]] ] = [[pointy stick croms lordgear hitto]],},
{[ [[w2keyword]] ] = [[eanruigo]],[ [[w1keyword]] ] = [[eanruigw]],[ [[w1name]] ] = [[- - - CALP IS RISEN - - -]],[ [[w2name]] ] = [[- - - - ALL HAIL! - - - -]],},
{[ [[w2name]] ] = [[Ore's stone disc]],[ [[w1keyword]] ] = [[oreweap1]],[ [[w1name]] ] = [[Ore's stone circle]],[ [[w2keyword]] ] = [[oreweap2]],},
{[ [[w2name]] ] = [[GTI RighT]],[ [[w1keyword]] ] = [[gti]],[ [[w1name]] ] = [[GTI LefT]],[ [[w2keyword]] ] = [[gti]],},
{[ [[w2name]] ] = [[a Pernach named "arccotmain"]],[ [[w1keyword]] ] = [[arccotoff]],[ [[w1name]] ] = [[Arccot's offhand shestopyor]],[ [[w2keyword]] ] = [[arccotmain]],},
}
