return {{[ [[Fango]] ] = {2},[ [[Ghaik]] ] = {3},[ [[Rancor]] ] = {4},[ [[Kaki]] ] = {5},[ [[Chiles]] ] = {6},[ [[Glitch]] ] = {7},[ [[Abelian]] ] = {8},[ [[Tavoli]] ] = {9},[ [[Ninehundred]] ] = {10},[ [[Volarys]] ] = {11},[ [[Gravman]] ] = {12},[ [[Kylise]] ] = {13},[ [[Asha]] ] = {14},[ [[Kali]] ] = {15},[ [[Cheddar]] ] = {16},[ [[Aginor]] ] = {17},[ [[Dazer]] ] = {18},[ [[Eanruig]] ] = {19},[ [[Blaset]] ] = {20},[ [[Claap]] ] = {21},[ [[Zygarth]] ] = {22},[ [[Kiron]] ] = {23},[ [[Language]] ] = {24},[ [[Vulkan]] ] = {25},[ [[Xanur]] ] = {26},[ [[Tysthet]] ] = {27},[ [[Photon]] ] = {28},[ [[Flood]] ] = {29},[ [[Sludge]] ] = {30},[ [[Spuati]] ] = {31},[ [[Rawil]] ] = {32},[ [[Meista]] ] = {33},[ [[NinehundreD]] ] = {34},[ [[Thirdeye]] ] = {35},[ [[Forseti]] ] = {36},[ [[Ramahdon]] ] = {37},[ [[Chronos]] ] = {38},[ [[Ore]] ] = {39},[ [[Gti]] ] = {40},[ [[Celeste]] ] = {41},},
{[ [[w1name]] ] = [[Green Destiny]],[ [[w1keyword]] ] = [[destiny]],},
{[ [[w2name]] ] = [[SPIN MOVE]],[ [[w1keyword]] ] = [[ramawield]],[ [[w1name]] ] = [[HE'S ON FIRE]],[ [[w2keyword]] ] = [[calpchak32b]],},
{[ [[w2name]] ] = [[Malevolence]],[ [[w1keyword]] ] = [[extir]],[ [[w1name]] ] = [[Extirpation]],[ [[w2keyword]] ] = [[malev]],},
{[ [[w1name]] ] = [[Frostie catches Snowflakes]],[ [[w1keyword]] ] = [[apple]],},
{[ [[w2name]] ] = [[pure psi-blade]],[ [[w1keyword]] ] = [[veng]],[ [[w1name]] ] = [[Great Vengeance]],[ [[w2keyword]] ] = [[chiles]],},
{[ [[w1name]] ] = [[Glitch]],[ [[w1keyword]] ] = [[glitch]],},
{[ [[w1name]] ] = [[A dragon-blade]],[ [[w1keyword]] ] = [[dragon bone blade sword hitgear]],},
{[ [[w2keyword]] ] = [[tavclawright]],[ [[w1keyword]] ] = [[tavclawleft]],[ [[w1name]] ] = [[Intinn]],[ [[w2name]] ] = [[Aigne]],},
{[ [[w1name]] ] = [[Gotcha!]],[ [[w1keyword]] ] = [[got]],},
{[ [[w2keyword]] ] = [[exantus]],[ [[w1keyword]] ] = [[excelsior]],[ [[w1name]] ] = [[Excelsior V]],[ [[w2name]] ] = [[Exantus V]],},
{[ [[w2keyword]] ] = [[gravman3]],[ [[w1keyword]] ] = [[gravman1]],[ [[w1name]] ] = [[gravmannnnn]],[ [[w2name]] ] = [[gravman]],},
{[ [[w1name]] ] = [[a saber of pure light]],[ [[w1keyword]] ] = [[ky]],},
{[ [[w2keyword]] ] = [[fear]],[ [[w1keyword]] ] = [[pain]],[ [[w1name]] ] = [[ Pain]],[ [[w2name]] ] = [[ Fear]],},
{[ [[w2name]] ] = [[Whispers of the Muse]],[ [[w1keyword]] ] = [[wrath]],[ [[w1name]] ] = [[Kali's Wrath]],[ [[w2keyword]] ] = [[calpchak42c4]],},
{[ [[w2keyword]] ] = [[calpchak2c]],[ [[w1keyword]] ] = [[calpchak32]],[ [[w1name]] ] = [[CHEDDAR]],[ [[w2name]] ] = [[CHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEZE]],},
{[ [[w2keyword]] ] = [[aginorwield]],[ [[w1keyword]] ] = [[aginoroffh]],[ [[w1name]] ] = [[Kiss of the Dragkhar]],[ [[w2name]] ] = [[Myrddraal's Blade]],},
{[ [[w2keyword]] ] = [[spuati]],[ [[w1keyword]] ] = [[snuffle]],[ [[w1name]] ] = [[manna hat rack]],[ [[w2name]] ] = [[a tan ham crank]],},
{[ [[w2keyword]] ] = [[eanruigo]],[ [[w1keyword]] ] = [[eanruigw]],[ [[w1name]] ] = [[Chondrite Longsword]],[ [[w2name]] ] = [[Chondrite Shortsword]],},
{[ [[w1name]] ] = [[Blaset's Blaset-ing Sword]],[ [[w1keyword]] ] = [[mandel]],},
{[ [[w1name]] ] = [[CLICK CLICK]],[ [[w1keyword]] ] = [[calpchak]],},
{[ [[w2name]] ] = [[zygarth]],[ [[w1keyword]] ] = [[zygarth]],[ [[w1name]] ] = [[Zygarth's silver sword]],},
{[ [[w2name]] ] = [[Loradon's Justice]],[ [[w1keyword]] ] = [[islene]],[ [[w1name]] ] = [[Islene's Fury]],[ [[w2keyword]] ] = [[loradon]],},
{[ [[w2name]] ] = [[Mandel's Great Sword]],[ [[w1keyword]] ] = [[mandeljar]],[ [[w1name]] ] = [[Mandel's Greater Sword]],[ [[w2keyword]] ] = [[mandeljaroff]],},
{[ [[w2keyword]] ] = [[lordkrd]],[ [[w1keyword]] ] = [[lordkdr]],[ [[w1name]] ] = [[A Winged Angel]],[ [[w2name]] ] = [[A Winged Devil]],},
{[ [[w2keyword]] ] = [[xanur.off]],[ [[w1keyword]] ] = [[xanur.wield]],[ [[w1name]] ] = [[Xanur's Masamune]],[ [[w2name]] ] = [[Xanur's Murasame]],},
{[ [[w1name]] ] = [[Malicious Whispers]],[ [[w1keyword]] ] = [[malicious]],},
{[ [[w1name]] ] = [[A winged angel]],[ [[w1keyword]] ] = [[wing]],},
{[ [[w1name]] ] = [[TICKLE FIGHT]],[ [[w1keyword]] ] = [[hitt]],},
{[ [[w2name]] ] = [[Sludge's fiery offhand]],[ [[w1keyword]] ] = [[sludgewield]],[ [[w1name]] ] = [[Sludge's fiery wield]],[ [[w2keyword]] ] = [[sludgeo]],},
{[ [[w2name]] ] = [[a tan ham crank]],[ [[w1keyword]] ] = [[snuffle]],[ [[w1name]] ] = [[manna hat rack]],[ [[w2keyword]] ] = [[spuati]],},
{[ [[w2keyword]] ] = [[rawil1]],[ [[w1keyword]] ] = [[rawil2]],[ [[w1name]] ] = [[a gnawed blood-splattered leg bone]],[ [[w2name]] ] = [[a gnawed blood-splattered arm bone]],},
{[ [[w2name]] ] = [[Revenant's Blade]],[ [[w1keyword]] ] = [[meistawield]],[ [[w1name]] ] = [[Sword of the Scourge]],[ [[w2keyword]] ] = [[meistaoffhand]],},
{[ [[w2name]] ] = [[*-<AGONY>-*]],[ [[w1keyword]] ] = [[pain]],[ [[w1name]] ] = [[*-<PAIN>-*]],[ [[ws2keyword]] ] = [[agony]],},
{[ [[w1name]] ] = [[Bacon Buster]],[ [[w1keyword]] ] = [[bacon]],},
{[ [[w2keyword]] ] = [[forseti]],[ [[w1keyword]] ] = [[forseti]],[ [[w1name]] ] = [[Fleshslicer]],[ [[w2name]] ] = [[Fleshrender]],},
{[ [[w2name]] ] = [[TICKLE FIGHT]],[ [[w1keyword]] ] = [[pointy stick crom lordgear hitt]],[ [[w1name]] ] = [[I AM BEYONCE, ALWAYS]],[ [[w2keyword]] ] = [[pointy stick croms lordgear hitto]],},
{[ [[w1name]] ] = [[Trained Attack Sprite]],[ [[w1keyword]] ] = [[sprite]],},
{[ [[w2name]] ] = [[Ore's stone disc]],[ [[w1keyword]] ] = [[oreweap1]],[ [[w1name]] ] = [[Ore's stone circle]],[ [[w2keyword]] ] = [[oreweap2]],},
{[ [[w2name]] ] = [[GTI RighT]],[ [[w1keyword]] ] = [[gti]],[ [[w1name]] ] = [[GTI LefT]],[ [[w2keyword]] ] = [[gti]],},
{[ [[w1name]] ] = [[a shiny sword]],[ [[w1keyword]] ] = [[15387031339]],},
}
