-------------------------------------------------
--          Folder for GUI scripts          --
--                                             --
-- Note that you can also use external scripts --
-------------------------------------------------
