-- Trigger: Hero Hit Gear 
-- Attribute: isActive


-- Trigger Patterns:
-- 0 (substring): a drow headdress
-- 1 (substring): david's sling
-- 2 (substring): a barbed crescent talisman
-- 3 (substring): black leather gloves
-- 4 (substring): torch of Flames
-- 5 (substring): an Orkenfyr signet ring
-- 6 (substring): leather of Crecy
-- 7 (substring): an amethyst circlet
-- 8 (substring): Crimsonscale skirt
-- 9 (substring): slagwalkers
-- 10 (substring): an alienskin arm brace
-- 11 (substring): Mistress Machadae's War Banner
-- 12 (substring): a jeweled scabbard
-- 13 (substring): an ice scale bracer
-- 14 (substring): seven-league boots
-- 15 (substring): a helm of Cherubims
-- 16 (substring): medallion of Justice
-- 17 (substring): flaming pants
-- 18 (substring): a scorpion tattoo
-- 19 (substring): the ring of Purity
-- 20 (substring): skinning gloves
-- 21 (substring): an ice ring
-- 22 (substring): death armor
-- 23 (substring): a dark dwarven brand
-- 24 (substring): a chained steel collar
-- 25 (substring): the symbol of darkness
-- 26 (substring): a shard of black Doom marble
-- 27 (substring): Fatewalkers
-- 28 (substring): ultimoose Power
-- 29 (substring): heroic dragonscale sleeves
-- 30 (substring): symbol of darkness
-- 31 (substring): banner of the Lone Wolf
-- 32 (substring): killing glove
-- 33 (substring): robe of greatness
-- 34 (substring): a great white battle axe
-- 35 (substring): a silver breast plate
-- 36 (substring): an orb of amorphous essence
-- 37 (substring): a half-pint sized sling

-- Script Code:
cecho (string.rep (" ",80-tonumber(string.len(line))) .. "<blue> [Hero Hit]")