-- Trigger: Alleg - Uncommon 
-- Attribute: isActive


-- Trigger Patterns:
-- 0 (substring): an iron dha
-- 1 (substring): a seething ball of blue flame
-- 2 (substring): a rock hammer
-- 3 (substring): a cape of angel feathers
-- 4 (substring): a lavabomb
-- 5 (substring): a green web veil
-- 6 (substring): clasp of eternal anguish
-- 7 (substring): an ice hound's tooth
-- 8 (substring): a small steam gun
-- 9 (substring): a unicorn horn
-- 10 (substring): an ice collar
-- 11 (substring): Ring of the white flame
-- 12 (substring): a diamond dagger
-- 13 (substring): a black whip
-- 14 (substring): a dancing katana
-- 15 (substring): a dancing rapier
-- 16 (substring): a stone hammer
-- 17 (substring): golden sleeves
-- 18 (substring): the Blade of Discord
-- 19 (substring): exotic robes
-- 20 (substring): devilish lance
-- 21 (substring): an aurora bow
-- 22 (substring): a radiance of wickedness
-- 23 (substring): stone platemail
-- 24 (substring): a dancing dagger
-- 25 (substring): a flametongue called 'Firebrand'
-- 26 (substring): signet of the Pure Flame
-- 27 (substring): the whip, "Death-Tamer"
-- 28 (substring): the staff of the lower planes
-- 29 (substring): panthrodrine-skin leggings
-- 30 (substring): an air gun
-- 31 (substring): vial of unfinished portal serum
-- 32 (substring): the mark of madness
-- 33 (substring): a storm-skin cloak
-- 34 (substring): a decaying vest made from cracked leather
-- 35 (substring): steel broadsword
-- 36 (substring): a crumpled note
-- 37 (substring): a viper fang
-- 38 (substring): a pair of wind-ravaged boots
-- 39 (substring): a stone disc
-- 40 (substring): shaleskin arm guard 

-- Script Code:
cecho (string.rep (" ",80-tonumber(string.len(line))) .. "<yellow> [ALLEG - Uncommon]")