-- Trigger: Alleg - Common 
-- Attribute: isActive


-- Trigger Patterns:
-- 0 (substring): a sacrificial knife
-- 1 (substring): a glowing iron skewer
-- 2 (substring): a bloodletter flail
-- 3 (substring): a buckler bracelet
-- 4 (substring): a dagger of dark rites
-- 5 (substring): an ethereal blade
-- 6 (substring): axe of the third plane
-- 7 (substring): an iron web shield
-- 8 (substring): green psi-blade
-- 9 (substring): yellow psi-blade
-- 10 (substring): clear psi-blade
-- 11 (substring): blue psi-blade
-- 12 (substring): a heavy shroud
-- 13 (substring): black master's hood
-- 14 (substring): the black sword of the keep
-- 15 (substring): dark purple robe
-- 16 (substring): a crude spear
-- 17 (substring): crystal ball
-- 18 (substring): a shard-embedded whip
-- 19 (substring): a black etched tablet
-- 20 (substring): a blueish-white stone
-- 21 (substring): amulet with a small silver sword inscribed on it
-- 22 (substring): a pair of kzinti slaughter gloves
-- 23 (substring): a golden bow
-- 24 (substring): assassin's armband
-- 25 (substring): a whirl of elusive feathers
-- 26 (substring): a devilish talisman
-- 27 (substring): silver dagger with a golden handle
-- 28 (substring): blood red robe
-- 29 (substring): black wand with a grinning skull
-- 30 (substring): an ice bow
-- 31 (substring): a incantation note
-- 32 (substring): coarse leather boots
-- 33 (substring): Faerie script
-- 34 (substring): shaleskin arm guard

-- Script Code:
cecho (string.rep (" ",80-tonumber(string.len(line))) .. "<yellow> [ALLEG - Common]")